### ISSUE TITLE
Stopped development

### ISSUE THREAD

**Issue by ghost** [welbornprod/glader#1]
Hi!
I'm bits57(I'd like to keep myself anonymous, at least for now).
I see you have cut development in 2017, and I'd like to ask you to open it again. I can contribute to this myself, I know how your code works as I've studied glader closely. I use it in my daily development with glade and GNOME Builder, and it has helped me a lot. I have already a list of things to change:

- Support for other main toplevels(gtkDialog, gtkFontChooserDialog, etc...)
- Better instructions on how to install gtkSourceView (I never got it to work, and eventually changed it to a gtkTextView from glader.glade, though this might be a problem on either my ubuntu install or in ubuntu itself, so I'm not excpecting this to change much)
- Compiled versions (.deb, .rpm) in Releases (I can do this)

If you don't want to do this, that's fine too! I can fork this to my github, but it would nice to co-develop this with the original author :).
Also, I'm not using my github every day so if you answer, I might not answer the same day. And since you're in the US, there is several hours between us.

Thank you
bits57
-

**Comment by cjwelborn** [comment]
@bits57, I wouldn't say I stopped development completely. I'm just taking a long break. I use glader every once in a while, and there are still things I would like to do with it. Send me a pull request, I'll be glad to merge anything that doesn't break glader. If you do fork it, I'd appreciate a name change. There will be features added to glader at some point, and it would be confusing to have two apps with the same name. I'd most likely end up pulling and patching any cool features you add anyway. Contributions are always welcome here, and I stay updated on my GitHub notifications.

**Comment by ghost** [comment]
Thanks! 
I've already done some experimental editing, but I'll make a pull request when they are fully stable. Keep it up!
